#!/bin/bash

echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:9091/alfresco/service/workspaces/master/elements/$1?evaluate=true"

curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:9091/alfresco/service/workspaces/master/elements/$1?evaluate=true"