#!/bin/bash

echo curl -w %{http_code}\n -X POST -u admin:admin -H Content-Type:application/json --data @JsonData/$1 http://localhost:9093/alfresco/service/workspaces/master/elements?expression=1%2B1
curl -w %{http_code}\n -X POST -u admin:admin -H Content-Type:application/json --data @JsonData/$1 http://localhost:9093/alfresco/service/workspaces/master/elements?expression=1%2B1