#!/bin/bash

echo curl -w "\"%{http_code}\n\"" -X POST -u admin:admin -H Content-Type:application/k --data @JsonData/$1 http://localhost:8080/alfresco/service/workspaces/master/elements?evaluate
curl -w "%{http_code}\n" -X POST -u admin:admin -H Content-Type:application/k --data @JsonData/$1 http://localhost:8080/alfresco/service/workspaces/master/elements?evaluate

