#!/bin/bash

echo curl -w "\n%{http_code}\n" -u admin:admin -X POST -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9093/alfresco/service/workspaces/master/elements?fix=true"

curl -w "\n%{http_code}\n" -u admin:admin -X POST -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9093/alfresco/service/workspaces/master/elements?fix=true"
