#!/bin/bash

if [ "$#" -eq 1 ]; then
  file=$1
  workspace=master
else
  file=$2
  workspace=$1
fi
if [[ ! -e "$file" ]]; then
  file="JsonData/"$file
fi
if [[ ! -e "$file" ]]; then
  echo "input file $file not found!"
  exit 1
fi

dataType=json

echo curl -w "\"\n%{http_code}\n\"" -u admin:admin -X POST -H "Content-Type:application/$dataType" --data @$file "\"http://localhost:8080/alfresco/service/workspaces/${workspace}/jobs\""
curl -w "\n%{http_code}\n" -u admin:admin -X POST -H "Content-Type:application/$dataType" --data @$file "http://localhost:8080/alfresco/service/workspaces/${workspace}/jobs"
