#!/bin/bash

echo curl -w "%{http_code} %{time_connect}:%{time_starttransfer}:%{time_total}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/jobs/$1?recurse=1";
curl -w "%{http_code} %{time_connect}:%{time_starttransfer}:%{time_total}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/jobs/$1?recurse=1" ;


