#!/bin/bash

export CURL_STATUS="-w \n%{http_code}\n"
export CURL_POST_FLAGS_NO_DATA="-X POST"
export CURL_POST_FLAGS="-X POST -H Content-Type:application/json --data"
export CURL_PUT_FLAGS="-X PUT"
export CURL_GET_FLAGS="-X GET"

export CURL_SECURITY=""

export CURL_USER=" -u admin:admin"
export CURL_FLAGS=$CURL_STATUS$CURL_USER$CURL_SECURITY

#pid=`${d}/getAlfrescoPid.sh`

if [ -z "$ALF_SERVER" ]; then
  export ALF_SERVER=localhost
fi

export SERVICE_URL="http://${ALF_SERVER}:8080/alfresco/service/"
export BASE_URL="http://${ALF_SERVER}:8080/alfresco/service/workspaces/master/"
