#!/bin/bash
if [ "$#" -eq 1 ]; then
  echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$1 "http://localhost:8080/alfresco/service/workspaces/master/elements"
  curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$1 "http://localhost:8080/alfresco/service/workspaces/master/elements"
else
  echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$2 "http://localhost:8080/alfresco/service/workspaces/$1/elements"
  curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @$2 "http://localhost:8080/alfresco/service/workspaces/$1/elements"
fi;

