#!/bin/bash

echo curl -w %{http_code}\n -X POST -u admin:admin http://localhost:9091/alfresco/service/workspaces/$1
curl -w %{http_code}\n -X POST -u admin:admin http://localhost:9091/alfresco/service/workspaces/$1