#!/bin/bash

if [ "$#" -eq 2 ] && [ $2 = 'recursive' ]; then
echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/elements/$1?recurse=true"
curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/workspaces/master/elements/$1?recurse=true"
else
echo curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/master/elements/$1"
curl -w "\n%{http_code}\n" -u admin:admin -X GET "http://localhost:8080/alfresco/service/workspaces/master/elements/$1"
fi;


