#!/bin/bash

echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9091/view-repo/service/javawebscripts/products"
curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9091/view-repo/service/javawebscripts/products"


echo curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9091/alfresco/service/workspaces/master/sites/europa/products"
curl -w "%{http_code}\n" -X POST -u admin:admin -H "Content-Type:application/json" --data @JsonData/$1 "http://localhost:9091/alfresco/service/workspaces/master/sites/europa/products"