#!/bin/bash


echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/workspaces/master/elements/$1"
curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/workspaces/master/elements/$1"

#echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/workspaces/master/views/$1"
#curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/workspaces/master/views/$1"
