#!/bin/bash

if [ "$#" -eq 1 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/diff?workspace1=master&workspace2=$1"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/diff?workspace1=master&workspace2=$1"
else
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/diff?workspace1=$1&workspace2=$2"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:9093/alfresco/service/diff?workspace1=$1&workspace2=$2"
fi;
