#!/bin/bash

if [ "$#" -eq 1 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/master/$1/latest/latest?changesForMerge"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/master/$1/latest/latest?changesForMerge"
elif [ "$#" -eq 2 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/$1/$2/latest/latest?changesForMerge"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/$1/$2/latest/latest?changesForMerge"
elif [ "$#" -eq 4 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/$1/$2/$3/$4?changesForMerge"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff/$1/$2/$3/$4?changesForMerge"
else
  echo "Error!  Expected 1, 2, or 4 args!"
fi;

