#!/bin/bash

if [ "$#" -eq 1 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=master&workspace2=$1"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=master&workspace2=$1"
elif [ "$#" -eq 2 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=$1&workspace2=$2"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=$1&workspace2=$2"
elif [ "$#" -eq 4 ]; then
  echo curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=$1&workspace2=$2&timestamp1=$3&timestamp2=$4"
  curl -w "%{http_code}\n" -X GET -u admin:admin "http://localhost:8080/alfresco/service/diff?workspace1=$1&workspace2=$2"
else
  echo "Error!  Expected 1, 2, or 4 args!"
fi;
